name: CI on Xamarin Android project

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Android
        run: |
          nuget restore
          cd FlensaApp
          cd FlensaApp.Android
          msbuild FlensaApp.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
